name: Reusable workflow
on:
  workflow_call:
    inputs:
      user-entered-git-tag:
        description: The Git tag to deploy - overrides the 'promote from lower environment' functionality
        required: false
        type: string
      test-val-1:
        required: true
        type: string
      test-val-2:
        required: true
        type: string

jobs:
  set-output:
    runs-on: ubuntu-latest
    steps:
      - name: set output
        id: set-output
        run: |
          ./compareVersions.sh \
            --user-entered-git-tag=${{ inputs.user-entered-git-tag }} \
            --currently-deployed-version=${{ inputs.test-val-1 }} \
            --version-to-deploy=${{ inputs.test-val-2 }}

      - name: run test
        id: run-test
        if: steps.set-output.outputs.should-deploy == 'true'
        run: echo "hi mom"
