name: Test workflow
env:
  NPM_AUTH_IDENT: '${{ secrets.NPM_AUTH_IDENT }}'
on:
  workflow_dispatch:
    inputs:
      git-tag:
        required: false
      test-val-1:
        required: true
      test-val-2:
        required: true
jobs:
  call-reusable-workflow:
    name: Deploy NGPOS to stage
    uses: andymueller85/advent_of_code_2022/.github/workflows/reusable.yml@main
    with:
      user-entered-git-tag: ${{ github.event.inputs.git-tag }}
      test-val-1: ${{ github.event.inputs.test-val-1 }}
      test-val-2: ${{ github.event.inputs.test-val-2 }}
